var photos = { 
    "img1":
        {"File": "images/photography/1_rice_fields.png", 
        "Column_Class": "photo-col1", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "15vw"},
    "img2":
        {"File": "images/photography/2_kaylee_rock.png", 
        "Column_Class": "photo-col2", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "15vw"},
    "img3":
        {"File": "images/photography/3_split_beach.png", 
        "Column_Class": "photo-col3", 
        "Width_Class": "photo_double", 
        "Caption": "", 
        "Vert_Position": "15vw"},
    "img4":
        {"File": "images/photography/4_beatrice_rock.png", 
        "Column_Class": "photo-col5", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "15vw"},
    "img5":
        {"File": "images/photography/5_jericho_sunset.png", 
        "Column_Class": "photo-col1", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "40.11vw;"},
    "img6":
        {"File": "images/photography/6_lisbon_buildings.png", 
        "Column_Class": "photo-col2", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "26.17vw"},
    "img7":
        {"File": "images/photography/7_joffre.png", 
        "Column_Class": "photo-col3", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "37.34vw;"},
    "img8":
        {"File": "images/photography/8_croatia_girls.png", 
        "Column_Class": "photo-col4", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "37.34vw;"},
    "img9":
        {"File": "images/photography/9_florence.png", 
        "Column_Class": "photo-col5", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "26.17vw;"},
    "img10":
        {"File": "images/photography/10_porto_house.png", 
        "Column_Class": "photo-col1", 
        "Width_Class": "photo_double", 
        "Caption": "", 
        "Vert_Position": "51.3vw;"},
    "img11":
        {"File": "images/photography/11_swiss.png", 
        "Column_Class": "photo-col3", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "48.5vw;"},
    "img12":
        {"File": "images/photography/12_bros_skate.png", 
        "Column_Class": "photo-col5", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "51.3vw;"},
    "img12_2":
        {"File": "images/photography/12_bergen_house.png", 
        "Column_Class": "photo-col4", 
        "Width_Class": "photo_double", 
        "Caption": "", 
        "Vert_Position": "62.6vw;"},
    "img13":
        {"File": "images/photography/13_bergen.png", 
        "Column_Class": "photo-col1", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "73.7vw;"},
    "img14":
        {"File": "images/photography/14_sky_train.png", 
        "Column_Class": "photo-col2", 
        "Width_Class": "photo_double", 
        "Caption": "", 
        "Vert_Position": "73.7vw;"},
    "img15":
        {"File": "images/photography/15_jasper.png", 
        "Column_Class": "photo-col4", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "84.9vw;"},
    "img16":
        {"File": "images/photography/16_split.png", 
        "Column_Class": "photo-col5", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "84.9vw;"},
    "img17":
        {"File": "images/photography/17_london.png", 
        "Column_Class": "photo-col1", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "98.8vw;"},
    "img18":
        {"File": "images/photography/18_hvar.png", 
        "Column_Class": "photo-col2", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "96.2vw;"},
    "img19":
        {"File": "images/photography/19_bench.png", 
        "Column_Class": "photo-col3", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "96.2vw;"},
    "img20":
        {"File": "images/photography/20_gyu.png", 
        "Column_Class": "photo-col3", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "110.1vw;"},
    "img21":
        {"File": "images/photography/21_cne.png", 
        "Column_Class": "photo-col4", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "96.2vw;"},
    "img22":
        {"File": "images/photography/22_chicago.png", 
        "Column_Class": "photo-col5", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "110vw;"},
    "img23":
        {"File": "images/photography/23_hanglige.png", 
        "Column_Class": "photo-col1", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "123.9vw;"},
    "img24":
        {"File": "images/photography/24_seagull.png", 
        "Column_Class": "photo-col2", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "121.5vw;"},
    "img25":
        {"File": "images/photography/25_banff_ice.png", 
        "Column_Class": "photo-col3", 
        "Width_Class": "photo_double", 
        "Caption": "", 
        "Vert_Position": "121.5vw;"},
    "img26":
        {"File": "images/photography/26_camino.png", 
        "Column_Class": "photo-col5", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "135.2vw;"},
    "img27":
        {"File": "images/photography/27_stockholm.png", 
        "Column_Class": "photo-col1", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "135vw;"},
    "img28":
        {"File": "images/photography/28_singapore.png", 
        "Column_Class": "photo-col2", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "132.9vw;"},
    "img29":
        {"File": "images/photography/29_bali.png", 
        "Column_Class": "photo-col3", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "143.9vw;"},
    "img30":
        {"File": "images/photography/30_jasper_ram.png", 
        "Column_Class": "photo-col4", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "143.9vw;"},
    "img31":
        {"File": "images/photography/31_diamond.png", 
        "Column_Class": "photo-col5", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "146.5vw;"},
    "img32":
        {"File": "images/photography/32_tofino.png", 
        "Column_Class": "photo-col1", 
        "Width_Class": "photo_double", 
        "Caption": "", 
        "Vert_Position": "158.2vw;"},
    "img33":
        {"File": "images/photography/33_swedish_fika.png", 
        "Column_Class": "photo-col3", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "169vw;"},
    "img34":
        {"File": "images/photography/34_hog.png", 
        "Column_Class": "photo-col4", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "155.1vw;"},
    "img35":
        {"File": "images/photography/35_peeps.png", 
        "Column_Class": "photo-col5", 
        "Width_Class": "photo_single", 
        "Caption": "", 
        "Vert_Position": "171.8vw;"},
}